### ISSUE TITLE
Include optional request properties in model browser add dialogs using an expand/collapse section

### ISSUE THREAD

**Issue by michpetrov** [hal/hal.next#121]
ModelBrowser - subsystems > datasources > xa-data-source > * > xa-datasource-properties

The add dialog shows only the "name" attribute because that's the only one required. However the "value" attribute is read-only so it cannot be edited later. Both attributes should be shown but I don't see a clear way for the form builder to identify this situation (the form builds from "request-properties" and those do not contain the "access-type").

**Comment by hpehl** [comment]
To do it in a generic way (and the model browser is generic), we should include the optional request properties as well. Since the number of optional properties might become quite large something like a expand/collapse section would be necessary [1].

[1] http://www.patternfly.org/pattern-library/forms-and-controls/expand-collapse-section/
